name: CI

on:
  - push
  - pull_request

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node_version: [12, 14, 16, 18]

    steps:
      - uses: actions/checkout@v2

      - name: Using node ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install
        run: npm ci

      - name: Test
        run: npm t
